### ISSUE TITLE
replace tailwind logos with bees or something!

### ISSUE THREAD

**Issue by otekolste** [otekolste/answer-hive#92]
Using tailwind docs change color of navbar to black and make logos yellow bees or beehive

**Comment by Ashleighjg** [comment]
https://github.com/otekolste/answer-hive/pull/100

![Image](https://github.com/user-attachments/assets/b1c790d5-f64c-4c5d-a6ec-19f1e43a2dcc)


I created a logo but couldn't use it because i'm unable to replace that image link successfully. For some reason it breaks when I try to insert any thing else other than icons.![Image](https://github.com/user-attachments/assets/cbde0276-8e4d-4552-bb71-cd7e0248520e)
